<?php

// Navigamus 2025 — the side programme ("doprovodný program") offered at registration.
// Its times are invented and its dates are a guess around Friday 6 June.
//
// The design is kissj's (~/prg/kissj/public/eventSpecificCss/stylesNavigamus25.css, with kissj's
// default dark palette for what that file leaves out), adjusted by eventApp's contrast rules:
// every role pair clears AA, large fills are pale in light mode and dark in dark mode, cards
// carry a tone step and a 3:1 hairline. Body text is neutral, not the event colour.
return [
    'name' => 'Navigamus 2025',
    'shortName' => 'Navigamus',
    'features' => ['programs', 'push', 'news'],
    'listed' => true,
    'dates' => ['start' => '2025-06-05', 'end' => '2025-06-08'],
    'theme' => ['radius' => '6px', 'radius-card' => '6px', 'radius-sheet' => '6px'],
    'colors' => [
        'background' => '#e6ebed',
        'link' => '#204c68',
        'base' => '#204c68',
        'darker' => '#06375a',
        'primary' => '#B72225',
        'text' => '#262626',
        'text-invert' => '#ffffff',
    ],

    'roles' => [
        'light' => [
            'ground' => '#e6ebed',
            'on-ground' => '#262626',
            'surface' => '#f9f9f9',
            'on-surface' => '#262626',
            'structure' => '#f9f9f9',
            'on-structure' => '#262626',
            'edge-width' => '1px',
            'edge' => '#636363',
            'action' => '#B72225',
            'on-action' => '#ffffff',
            'action-link' => '#204c68',
            'tonal' => '#dfe4e8',
            'on-tonal' => '#204c68',
            'state' => '#204c68',
            'on-state' => '#ffffff',
            'heading' => '#06375a',
            'emphasis' => '#06375a',
            'scrim' => '#141414',
            'view-state' => '#204c68',
            'on-view-state' => '#ffffff',
            'field' => '#ffffff',
            'on-field' => '#262626',
            'sheet' => '#f9f9f9',
            'on-sheet' => '#262626',
            'sheet-action' => '#B72225',
            'on-sheet-action' => '#ffffff',
            'grid' => '#d8dddf',
            'grid-structure' => '#ffffff',
            'on-grid-structure' => '#141414',
            'grid-edge' => '#7d7e7f',
            'signature' => '#c3ced5',
            'on-signature' => '#06375a',
            'stage' => '#c1c5c7',
            'on-stage' => '#262626',
            'hairline' => '#636363',
            'registered-bg' => '#204c68',
            'registered-line' => '#636363',
            'registered-width' => '1px',
        ],
        'dark' => [
            'ground' => '#212121',
            'on-ground' => '#ececec',
            'surface' => '#252525',
            'on-surface' => '#ececec',
            'structure' => '#212121',
            'on-structure' => '#ececec',
            'edge-width' => '1px',
            'edge' => '#70949b',
            'action' => '#EE2542',
            'on-action' => '#000000',
            'action-link' => '#57A0AD',
            'tonal' => '#2e3b3d',
            'on-tonal' => '#ffffff',
            'state' => '#57A0AD',
            'on-state' => '#141414',
            'heading' => '#57A0AD',
            'emphasis' => '#57A0AD',
            'scrim' => '#000000',
            'view-state' => '#57A0AD',
            'on-view-state' => '#141414',
            'field' => '#2f2f2f',
            'on-field' => '#ececec',
            'sheet' => '#252525',
            'on-sheet' => '#ececec',
            'sheet-action' => '#EE2542',
            'on-sheet-action' => '#000000',
            'grid' => '#191919',
            'grid-structure' => '#2f2f2f',
            'on-grid-structure' => '#ececec',
            'grid-edge' => '#5f5f5f',
            'signature' => '#2d3d40',
            'on-signature' => '#ffffff',
            'stage' => '#2e2e2e',
            'on-stage' => '#ececec',
            'hairline' => '#888888',
            'registered-bg' => '#57A0AD',
            'registered-line' => '#888888',
            'registered-width' => '1px',
        ],
    ],
    // the white-disc drawing is for the app bar, which is filled with the navy event colour
    'assets' => ['menuLogo' => 'events/navigamus25/logo_navigamus25_trans_bg_168.png', 'menuLogoOnState' => 'events/navigamus25/logo_navigamus25_white_bg_172.png', 'mainLogo' => 'events/navigamus25/logo_navigamus25_trans_bg_168.png', 'notificationIcon' => 'events/navigamus25/logo_navigamus25_trans_bg_168.png'],
    'homepage' => ['footerText' => '', 'footerLinkLabel' => '', 'footerLinkHref' => ''],
];
