<?php

// Miquik 2026 — unlisted. Its date is invented.
//
// The design is kissj's default palette (~/prg/kissj/public/styles.css), which kissj's Miquik
// event type uses, adjusted by eventApp's contrast rules: every role pair clears AA, large fills
// are pale in light mode and dark in dark mode, cards carry a tone step and a 3:1 hairline.
// Body text is neutral, not the event colour. kissj has no Miquik logo.
return [
    'name' => 'Miquik 2026',
    'shortName' => 'Miquik',
    'features' => ['programs', 'push', 'news'],
    'theme' => ['radius' => '6px', 'radius-card' => '6px', 'radius-sheet' => '6px'],
    'colors' => [
        'background' => '#e6ebed',
        'link' => '#000000',
        'base' => '#0D71B9',
        'darker' => '#06375a',
        'primary' => '#b9550d',
        'text' => '#262626',
        'text-invert' => '#ffffff',
    ],

    'roles' => [
        'light' => [
            'ground' => '#e6ebed',
            'on-ground' => '#262626',
            'surface' => '#f9f9f9',
            'on-surface' => '#262626',
            'structure' => '#f9f9f9',
            'on-structure' => '#262626',
            'edge-width' => '1px',
            'edge' => '#636363',
            'action' => '#b9550d',
            'on-action' => '#ffffff',
            'action-link' => '#000000',
            'tonal' => '#dde9f1',
            'on-tonal' => '#06375a',
            'state' => '#0D71B9',
            'on-state' => '#ffffff',
            'heading' => '#06375a',
            'emphasis' => '#06375a',
            'scrim' => '#141414',
            'view-state' => '#0D71B9',
            'on-view-state' => '#ffffff',
            'field' => '#ffffff',
            'on-field' => '#262626',
            'sheet' => '#f9f9f9',
            'on-sheet' => '#262626',
            'sheet-action' => '#b9550d',
            'on-sheet-action' => '#ffffff',
            'grid' => '#d8dddf',
            'grid-structure' => '#ffffff',
            'on-grid-structure' => '#141414',
            'grid-edge' => '#7d7e7f',
            'signature' => '#bed7e9',
            'on-signature' => '#06375a',
            'stage' => '#c1c5c7',
            'on-stage' => '#262626',
            'hairline' => '#636363',
            'registered-bg' => '#0D71B9',
            'registered-line' => '#636363',
            'registered-width' => '1px',
        ],
        'dark' => [
            'ground' => '#212121',
            'on-ground' => '#ececec',
            'surface' => '#252525',
            'on-surface' => '#ececec',
            'structure' => '#212121',
            'on-structure' => '#ececec',
            'edge-width' => '1px',
            'edge' => '#8695ae',
            'action' => '#d5b885',
            'on-action' => '#141414',
            'action-link' => '#85A2D5',
            'tonal' => '#363c45',
            'on-tonal' => '#ffffff',
            'state' => '#85A2D5',
            'on-state' => '#141414',
            'heading' => '#85A2D5',
            'emphasis' => '#85A2D5',
            'scrim' => '#000000',
            'view-state' => '#85A2D5',
            'on-view-state' => '#141414',
            'field' => '#2f2f2f',
            'on-field' => '#ececec',
            'sheet' => '#252525',
            'on-sheet' => '#ececec',
            'sheet-action' => '#d5b885',
            'on-sheet-action' => '#141414',
            'grid' => '#191919',
            'grid-structure' => '#2f2f2f',
            'on-grid-structure' => '#ececec',
            'grid-edge' => '#5f5f5f',
            'signature' => '#373d49',
            'on-signature' => '#ffffff',
            'stage' => '#2e2e2e',
            'on-stage' => '#ececec',
            'hairline' => '#888888',
            'registered-bg' => '#85A2D5',
            'registered-line' => '#888888',
            'registered-width' => '1px',
        ],
    ],
    'assets' => ['menuLogo' => '', 'mainLogo' => ''],
    'homepage' => ['footerText' => '', 'footerLinkLabel' => '', 'footerLinkHref' => ''],
];
